# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.textChanged.connect(self.search)
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Поиск на Титанике"))
        self.label.setText(_translate("MainWindow", "Подстрока для поиска:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PassengerID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sex"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Survived"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SexCode"))

        import csv
        with open('titanic.csv', encoding="utf8") as csvfile:
            reader = csv.reader(csvfile, delimiter=',', quotechar='"')
            for index, row in enumerate(reader):
                if index != 0:
                    if int(row[-2]) == 1:
                        color = 0, 255, 0
                    else:
                        color = 255, 0, 0
                    rowPosition = self.tableWidget.rowCount()
                    self.tableWidget.insertRow(rowPosition)
                    new_item = QtWidgets.QTableWidgetItem(row[0])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 0, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[1])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 1, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[2])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 2, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[3])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 3, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[4])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 4, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[5])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 5, new_item)
                    new_item = QtWidgets.QTableWidgetItem(row[6])
                    new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                    self.tableWidget.setItem(rowPosition, 6, new_item)

    def search(self):
        while self.tableWidget.rowCount() > 0:
            self.tableWidget.removeRow(0)
        if len(self.lineEdit.text()) >= 3:
            import csv
            with open('titanic.csv', encoding="utf8") as csvfile:
                reader = csv.reader(csvfile, delimiter=',', quotechar='"')
                for index, row in enumerate(reader):
                    if index != 0:
                        if int(row[-2]) == 1:
                            color = 0, 255, 0
                        else:
                            color = 255, 0, 0
                        if self.lineEdit.text().lower() in row[1].lower():
                            rowPosition = self.tableWidget.rowCount()
                            self.tableWidget.insertRow(rowPosition)
                            new_item = QtWidgets.QTableWidgetItem(row[0])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 0, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[1])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 1, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[2])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 2, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[3])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 3, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[4])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 4, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[5])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 5, new_item)
                            new_item = QtWidgets.QTableWidgetItem(row[6])
                            new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                            self.tableWidget.setItem(rowPosition, 6, new_item)
        else:
            import csv
            with open('titanic.csv', encoding="utf8") as csvfile:
                reader = csv.reader(csvfile, delimiter=',', quotechar='"')
                for index, row in enumerate(reader):
                    if index != 0:
                        if int(row[-2]) == 1:
                            color = 0, 255, 0
                        else:
                            color = 255, 0, 0
                        rowPosition = self.tableWidget.rowCount()
                        self.tableWidget.insertRow(rowPosition)
                        new_item = QtWidgets.QTableWidgetItem(row[0])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 0, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[1])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 1, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[2])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 2, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[3])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 3, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[4])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 4, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[5])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 5, new_item)
                        new_item = QtWidgets.QTableWidgetItem(row[6])
                        new_item.setBackground(QtGui.QBrush(QtGui.QColor(*color)))
                        self.tableWidget.setItem(rowPosition, 6, new_item)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
